config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root   'static_pages#home'
  get    '/about',   to: 'static_pages#about'
  get    '/news',   to: 'static_pages#news'
  get    '/cheap',   to: 'static_pages#Cheap'
  get    '/mid',   to: 'static_pages#Mid'
  get    '/expensive',   to: 'static_pages#Expensive'
  get    '/buy',   to: 'static_pages#Buy'
  get    '/finish',   to: 'static_pages#Finish'
  get    '/micropost', to: 'static_pages#contact'
  get    '/users', to: 'users#index'
  get    'static_pages/news'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :microposts,          only: [:create, :destroy]
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate  :picture_size

  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 60 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 260 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
 
  def feed
    Micropost.where("user_id = ?", id)
  end
  
  class << self     
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
  
    def new_token
      SecureRandom.urlsafe_base64
    end
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    if remember_digest.nil?
       false
    else
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/contact'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private

    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end
    
    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
     
  end
  
  def about
  end

  def contact
   if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
   end
  end

  def news
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  
  def index
     @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end
  
  def new
    @user = User.new
  end
  
  def index
    @users = User.all
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
  end
  
   private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Paladin PC Application"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end  
  
  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
   # def gravatar_for(user, size: 80)
    #    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
     #   gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
     #   image_tag(gravatar_url, alt: user.name, class: "gravatar")
    #end
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <nav>
        <ul>
            <li><%= link_to "About",   about_path %></li>
            <li><%= link_to "Micropost", micropost_path %></li>
            <li><%= link_to "News", news_path %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Sign up",   signup_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  
  </span>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/Buy.html.erb
<div class="checkout-panel">
  <div class="panel-body">
    <h1 class="title">Checkout</h1>
    
    <div class="input-fields">
      <div class="column-1">
        <label for="cardholder">Cardholder's Name (First Last)</label>
        <input type="text" id="cardholder" />
 
        <div class="small-inputs">
          <div>
            <label for="date">Valid thru (mm/yy)</label>
            <input type="text" id="date"/>
          </div>
 
          <div>
            <label for="verification">CVV / CVC * (3 digitS)</label>
            <input type="password" id="verification"/>
          </div>
        </div>
 
      </div>
      <div class="column-2">
        <label for="cardnumber">Card Number (16 digit number)</label>
        <input type="password" id="cardnumber"/>
      </div>
    </div>
  </div>
    <button id="nextButton" class="btn" >Finished</button>
        <script type="text/javascript">
            document.getElementById("nextButton").onclick = function () {
                location.href = "/finish";
            };
        </script>
</div>

app/views/static_pages/Cheap.html.erb
<% provide(:title, "Home") %>
<head>
 
        <title>CSCI450</title>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="stylesheets/custom.scss">
    </head>
    <body>
        
        <h1>Low End PC</h1>
        <h2>$450-$900</h2><br>
      
        <img src="/assets/cheap1.png" style="width:250px;height:300px;border:10;"/>
      
         <button id="Cheap1Button" class="button2">$450</button>
            <script type="text/javascript">
                document.getElementById("Cheap1Button").onclick = function () {
                    location.href = "/buy";
                };
            </script>
            
        <img src="/assets/cheap2.png" style="width:250px;height:300px;border:0;"/>
                
        <button id="Cheap2Button" class="button2" >$650</button>
            <script type="text/javascript">
                document.getElementById("Cheap2Button").onclick = function () {
                    location.href = "/buy";
                };
            </script><br><br>
        
        <img src="/assets/cheap3.png" style="width:250px;height:300px;border:0;"/>
        
        <button id="Cheap3Button" class="button2" >$750</button>
            <script type="text/javascript">
                document.getElementById("Cheap3Button").onclick = function () {
                    location.href = "/buy";
                };
            </script>
            
        <img src="/assets/cheap4.png" style="width:250px;height:300px;border:0;"/>
        
        <button id="Cheap4Button" class="button2" >$900</button>
            <script type="text/javascript">
                document.getElementById("Cheap4Button").onclick = function () {
                    location.href = "/buy";
                };
            </script>
    </body>

app/views/static_pages/Expensive.html.erb
<% provide(:title, "Home") %>
<head>
 
        <title>CSCI450</title>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="stylesheets/custom.scss">
    </head>
    <body>
        
        <h1>High End PC</h1>
        <h2>$2500-$5000</h2><br>
      
        <img src="/assets/ex1.png" style="width:250px;height:300px;border:10;"/>
        <button id="Ex1Button" class="button2">$2500</button>
            <script type="text/javascript">
                document.getElementById("Ex1Button").onclick = function () {
                    location.href = "/buy";
                };
            </script>
        
        <img src="/assets/ex3.png" style="width:250px;height:300px;border:10;"/>
        
        <button id="Ex2Button" class="button2" >$3000</button>
            <script type="text/javascript">
                document.getElementById("Ex2Button").onclick = function () {
                    location.href = "/buy";
                };
            </script><br><br>
        
        <img src="/assets/ex2.png" style="width:250px;height:300px;border:10;"/>
        
        <button id="Ex3Button" class="button2" >$4000</button>
            <script type="text/javascript">
                document.getElementById("Ex3Button").onclick = function () {
                    location.href = "/buy";
                };
            </script>
        
        <img src="/assets/ex4.png" style="width:250px;height:300px;border:10;"/>
        
        <button id="Ex4Button" class="button2" >$5000</button>
            <script type="text/javascript">
                document.getElementById("Ex4Button").onclick = function () {
                    location.href = "/buy";
                };
            </script>
    </body>

app/views/static_pages/Finish.html.erb
<% provide(:title, "Home") %>
<head>
    <title>CSCI450</title>
     <meta charset="utf-8">
     <link rel="stylesheet" type="text/css" href="stylesheets/custom.scss">
</head>
<body>
    <h1>Thanks!</h1>
    <h2>Your purchase was confirmed. Your PC will be delivered in 7-10 business days.</h2><br>
</body>

app/views/static_pages/Mid.html.erb
<% provide(:title, "Home") %>
<head>
 
        <title>CSCI450</title>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="stylesheets/custom.scss">
    </head>
    <body>
        
        <h1>Mid Tier PC</h1>
        <h2>$1200-$2300</h2><br>
      
        <img src="/assets/mid1.png" style="width:250px;height:300px;border:10;"/>
      
         <button id="Mid1Button" class="button2">$1200</button>
            <script type="text/javascript">
                document.getElementById("Mid1Button").onclick = function () {
                    location.href = "/buy";
                };
            </script>
        
        <img src="/assets/mid2.png" style="width:250px;height:300px;border:10;"/>
        
        <button id="Mid2Button" class="button2" >$1500</button>
            <script type="text/javascript">
                document.getElementById("Mid2Button").onclick = function () {
                    location.href = "/buy";
                };
            </script><br><br>
            
        <img src="/assets/mid3.png" style="width:250px;height:300px;border:10;"/>
        
        <button id="Mid3Button" class="button2" >$1800</button>
            <script type="text/javascript">
                document.getElementById("Mid3Button").onclick = function () {
                    location.href = "/buy";
                };
            </script>
        
        <img src="/assets/mid4.png" style="width:250px;height:300px;border:10;"/>
        
        <button id="Mid4Button" class="button2" >$2300</button>
            <script type="text/javascript">
                document.getElementById("Mid4Button").onclick = function () {
                    location.href = "/buy";
                };
            </script>
    </body>

app/views/static_pages/about.html.erb
<% provide(:title, "Home") %>
<h1>About Us</h1>

 <img src="/assets/home1.png" style="width:1150px;height:300px;border:0;"/><br><br>
 
 
<h2>Paladin PC is a computer building service that allows the user to sign up and select the amount
    of money they want to pay for a computer. Then a computer is made for them within their budget and shipped to them
    in 7-10 business days. They can also post reviews through the micropost section of the website. 
    As a basic website it is very simple to buy your computer and as we continue to grow we will update the website 
    to make it more customizable for the user.</h2>

app/views/static_pages/contact.html.erb
<% provide(:title, "Home") %>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
   <%= render root_path %>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<head>
 
        <title>CSCI450</title>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="stylesheets/custom.scss">
    </head>
    <body>
        
        <h1>Paladin PC</h1>
        <h2>You buy it, we build it.</h2><br>
        <img src="/assets/home1.png" style="width:1150px;height:300px;border:0;"/><br><br><br>
        
         <button id="CheapButton" class="button">Low End</button>
            <script type="text/javascript">
                document.getElementById("CheapButton").onclick = function () {
                    location.href = "/cheap";
                };
            </script>
        <button id="MidButton" class="button" >Mid Tier</button>
            <script type="text/javascript">
                document.getElementById("MidButton").onclick = function () {
                    location.href = "mid";
                };
            </script>
        <button id="ExpensiveButton" class="button" >High End</button>
            <script type="text/javascript">
                document.getElementById("ExpensiveButton").onclick = function () {
                    location.href = "expensive";
                };
            </script>
    </body>

app/views/static_pages/news.html.erb
<% provide(:title, "Home") %>
<h1>Computer News</h1>
<a href="https://www.reddit.com/r/pcmasterrace/">Link to reddits r/pcmasterrace where you can see what is new and trendy in the pc world.</a>

app/views/user/email:string.html.erb
<h1>User#email:string</h1>
<p>Find me in app/views/user/email:string.html.erb</p>

app/views/user/name:string.html.erb
<h1>User#name:string</h1>
<p>Find me in app/views/user/name:string.html.erb</p>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>



<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>